# Generated by Django 6.0.3 on 2026-03-29 03:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceShiftChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('certificate_text', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'substation__substation_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('designation_short', models.CharField(max_length=40)),
                ('cpf_no', models.CharField(blank=True, max_length=50)),
                ('weekly_off_day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_general_duty_operator', models.BooleanField(default=False)),
                ('employee_type', models.CharField(choices=[('operator', 'Operator'), ('tech_engineer', 'Tech / Engineer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['substation__substation_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('certificate_text', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('night_shift_allowance_units', models.PositiveIntegerField(default=0)),
                ('night_shift_rate', models.DecimalField(decimal_places=2, default=Decimal('190.00'), max_digits=10)),
            ],
            options={
                'ordering': ['-year', '-month', 'substation__substation_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substation_name', models.CharField(max_length=200)),
                ('om_name', models.CharField(max_length=200, verbose_name='O&M Name')),
                ('sub_division_name', models.CharField(max_length=200)),
                ('remark', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['substation_name'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceShiftRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('designation_short', models.CharField(max_length=40)),
                ('cpf_no', models.CharField(blank=True, max_length=50)),
                ('shift_days', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='easy.advanceshiftchart')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easy.employee')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAttendanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('designation_short', models.CharField(max_length=40)),
                ('cpf_no', models.CharField(blank=True, max_length=50)),
                ('attendance_days', models.JSONField(blank=True, default=dict)),
                ('shift_days', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easy.employee')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='easy.operatorattendancesheet')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.substation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='easy.substation'),
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.substation'),
        ),
        migrations.CreateModel(
            name='TechAttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('certificate_text', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.substation')),
            ],
            options={
                'ordering': ['-year', '-month', 'substation__substation_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechAttendanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('designation_short', models.CharField(max_length=40)),
                ('cpf_no', models.CharField(blank=True, max_length=50)),
                ('attendance_days', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easy.employee')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='easy.techattendancesheet')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='operatorattendancesheet',
            constraint=models.UniqueConstraint(fields=('substation', 'month', 'year'), name='unique_operator_sheet_per_month'),
        ),
        migrations.AddConstraint(
            model_name='advanceshiftchart',
            constraint=models.UniqueConstraint(fields=('substation', 'month', 'year'), name='unique_advance_sheet_per_month'),
        ),
        migrations.AddConstraint(
            model_name='techattendancesheet',
            constraint=models.UniqueConstraint(fields=('substation', 'month', 'year'), name='unique_tech_sheet_per_month'),
        ),
    ]
