# Generated by Django 6.0.3 on 2026-03-29 05:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def _vacant_name(index):
    return 'Vacant' if index == 1 else f'Vacant{index}'


def backfill_night_allowance_entries(apps, schema_editor):
    OperatorAttendanceSheet = apps.get_model('easy', 'OperatorAttendanceSheet')
    OperatorAttendanceRow = apps.get_model('easy', 'OperatorAttendanceRow')
    Employee = apps.get_model('easy', 'Employee')
    EasyNightAllowanceEntry = apps.get_model('easy', 'EasyNightAllowanceEntry')

    for sheet in OperatorAttendanceSheet.objects.all().order_by('id'):
        source_rows = list(OperatorAttendanceRow.objects.filter(sheet_id=sheet.id).order_by('sort_order', 'id')[:4])
        if source_rows:
            sources = [
                {
                    'employee_id': row.employee_id,
                    'display_name': row.employee_name or f'Employee {index}',
                }
                for index, row in enumerate(source_rows, start=1)
            ]
        else:
            operator_employees = list(
                Employee.objects.filter(substation_id=sheet.substation_id, employee_type='operator').order_by('id')[:4]
            )
            sources = [
                {
                    'employee_id': employee.id,
                    'display_name': employee.employee_name,
                }
                for employee in operator_employees
            ]

        vacant_index = 1
        for serial_no in range(1, 5):
            source = sources[serial_no - 1] if serial_no <= len(sources) else None
            if source:
                display_name = source['display_name']
                employee_id = source['employee_id']
                rate = sheet.night_shift_rate
            else:
                display_name = _vacant_name(vacant_index)
                employee_id = None
                rate = None
                vacant_index += 1

            night_count = sheet.night_shift_allowance_units if serial_no == 1 else None
            amount = (Decimal(night_count) * rate) if night_count is not None and rate is not None else None

            EasyNightAllowanceEntry.objects.create(
                operator_month_id=sheet.id,
                employee_id=employee_id,
                display_name=display_name,
                serial_no=serial_no,
                night_count=night_count,
                rate=rate,
                amount=amount,
                remark='Imported from earlier summary' if serial_no == 1 and night_count else '',
            )


def clear_night_allowance_entries(apps, schema_editor):
    EasyNightAllowanceEntry = apps.get_model('easy', 'EasyNightAllowanceEntry')
    EasyNightAllowanceEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyNightAllowanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('serial_no', models.PositiveSmallIntegerField()),
                ('night_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_allowance_entries', to='easy.employee')),
                ('operator_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_allowance_entries', to='easy.operatorattendancesheet')),
            ],
            options={
                'ordering': ['serial_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('operator_month', 'serial_no'), name='unique_night_allowance_row_per_sheet')],
            },
        ),
        migrations.RunPython(backfill_night_allowance_entries, clear_night_allowance_entries),
    ]
