# Generated by Django 6.0.3 on 2026-03-29 09:45

import django.db.models.deletion
import easy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0002_easynightallowanceentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('tech_engineer', 'Technician / Engineer'), ('apprentice', 'Apprentice'), ('outsource', 'Outsource')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApprenticeAttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('certificate_text', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.substation')),
            ],
            options={
                'ordering': ['-year', '-month', 'substation__substation_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprenticeAttendanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('designation_short', models.CharField(max_length=40)),
                ('cpf_no', models.CharField(blank=True, max_length=50)),
                ('attendance_days', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easy.employee')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='easy.apprenticeattendancesheet')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
            bases=(easy.models.EmployeeDisplayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OutsourceAttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('certificate_text', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy.substation')),
            ],
            options={
                'ordering': ['-year', '-month', 'substation__substation_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutsourceAttendanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('designation_short', models.CharField(max_length=40)),
                ('cpf_no', models.CharField(blank=True, max_length=50)),
                ('attendance_days', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easy.employee')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='easy.outsourceattendancesheet')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
            bases=(easy.models.EmployeeDisplayMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='apprenticeattendancesheet',
            constraint=models.UniqueConstraint(fields=('substation', 'month', 'year'), name='unique_apprentice_sheet_per_month'),
        ),
        migrations.AddConstraint(
            model_name='outsourceattendancesheet',
            constraint=models.UniqueConstraint(fields=('substation', 'month', 'year'), name='unique_outsource_sheet_per_month'),
        ),
    ]
