# Generated by Django 6.0.3 on 2026-03-29 14:10

import re

from django.db import migrations, models


VACANT_NAME_PATTERN = re.compile(r'^vacant(?:\d+)?$', re.IGNORECASE)


def is_vacant_name(name):
    return bool(VACANT_NAME_PATTERN.fullmatch((name or '').strip()))


def backfill_vacant_rows(apps, schema_editor):
    Employee = apps.get_model('easy', 'Employee')
    OperatorAttendanceRow = apps.get_model('easy', 'OperatorAttendanceRow')

    vacant_employee_ids = []
    for employee in Employee.objects.all().only('id', 'employee_name'):
        if is_vacant_name(employee.employee_name):
            vacant_employee_ids.append(employee.pk)

    if vacant_employee_ids:
        Employee.objects.filter(pk__in=vacant_employee_ids).update(is_vacant=True)

    for row in OperatorAttendanceRow.objects.all().only('id', 'employee_id', 'employee_name', 'attendance_days'):
        row_is_vacant = row.employee_id in vacant_employee_ids or is_vacant_name(row.employee_name)
        if not row_is_vacant:
            continue

        cleaned_attendance_days = {
            key: '' if value in {'P', 'off', None} else value
            for key, value in (row.attendance_days or {}).items()
        }
        OperatorAttendanceRow.objects.filter(pk=row.pk).update(
            is_vacant=True,
            attendance_days=cleaned_attendance_days,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0003_alter_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operatorattendancerow',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_vacant_rows, migrations.RunPython.noop),
    ]
