# Generated by Django 6.0.3 on 2026-03-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0004_employee_is_vacant_operatorattendancerow_is_vacant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('tech_engineer', 'Technician / Engineer'), ('apprentice', 'Apprentice'), ('outsource', 'Outsource'), ('other', 'Other')], max_length=20),
        ),
    ]
