# Generated by Django 6.0.3 on 2026-04-02 16:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0005_employee_joining_date_employee_working_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OperatorLogicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_operator_count', models.PositiveSmallIntegerField(default=4)),
                ('rotation_pattern', models.CharField(default='off,II,III,I,II,III,I', max_length=200)),
                ('general_duty_enabled', models.BooleanField(default=True)),
                ('general_duty_fallback_shift', models.CharField(default='G', max_length=20)),
                ('night_allowance_rate', models.DecimalField(decimal_places=2, default=Decimal('190.00'), max_digits=10)),
                ('allow_vacant_rows', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='approval_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advanceshiftchart',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apprenticeattendancesheet',
            name='approval_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apprenticeattendancesheet',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='apprenticeattendancesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeattendancesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apprenticeattendancesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeattendancesheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='approval_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorattendancesheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outsourceattendancesheet',
            name='approval_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outsourceattendancesheet',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='outsourceattendancesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsourceattendancesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outsourceattendancesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outsourceattendancesheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techattendancesheet',
            name='approval_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='techattendancesheet',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='techattendancesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techattendancesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techattendancesheet',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techattendancesheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_submitted_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubstationLogicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_substations', to='easy.operatorlogicconfig')),
                ('substation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logic_assignment', to='easy.substation')),
            ],
            options={
                'ordering': ['substation__substation_name'],
            },
        ),
    ]
