# Generated by Django 6.0.3 on 2026-04-02 17:08

from django.db import migrations, models


def backfill_working_place(apps, schema_editor):
    mapping = [
        ('OperatorAttendanceRow', 'employee'),
        ('AdvanceShiftRow', 'employee'),
        ('TechAttendanceRow', 'employee'),
        ('ApprenticeAttendanceRow', 'employee'),
        ('OutsourceAttendanceRow', 'employee'),
    ]
    for model_name, employee_field in mapping:
        model = apps.get_model('easy', model_name)
        for row in model.objects.select_related(employee_field).all():
            employee = getattr(row, employee_field, None)
            if employee and getattr(employee, 'working_place', None) and not row.working_place:
                row.working_place = employee.working_place
                row.save(update_fields=['working_place'])


class Migration(migrations.Migration):

    dependencies = [
        ('easy', '0006_appsetting_operatorlogicconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceshiftrow',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apprenticeattendancerow',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operatorattendancerow',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='outsourceattendancerow',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='techattendancerow',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(backfill_working_place, migrations.RunPython.noop),
    ]
